spring.application.name=Microservice_eureka
# Establece el puerto en el que correrá el servidor de Eureka
server.port=8761

# Le decimos a Eureka que este es el servidor, por lo tanto:
# No intentes registrarte a ti mismo como un cliente.
eureka.client.register-with-eureka=false

# No intentes buscar otros servicios (él es la fuente de información).
eureka.client.fetch-registry=false
# Deshabilitar la necesidad de un Config Server al arrancar
spring.cloud.config.enabled=false