spring.application.name=Microservice_course
# 2. Asigna un puerto diferente al de Eureka (que está en 8761)
server.port=8081

# 3. Dile dónde está el servidor Eureka para que pueda registrarse
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/